!===============================================================================
! 3dtri_BP8.f90
!
! SEAS Benchmark BP8-QD-GS: quasi-dynamic rate-and-state slip on a planar
! fault in an elastic whole-space, driven by pore-pressure diffusion from a
! Gaussian-regularized point injection at the fault center.
!
! Adapted from src/3dtri_BP5.f90's proven numerical machinery (MPI element
! decomposition matching NikkhooWalter2015/calc_nikkhoo_fs.f90's Scatterv
! scheme, and the Cash-Karp adaptive RK integrator rkqs/rkck, copied here
! near-verbatim) rather than its friction/output code, which does not fit
! this problem: BP5/BP6 track a single scalar slip-rate DOF with a fixed
! rake reconstructed from direction cosines (phy1,phy2), and use a 1D
! line-source pore-pressure solution (phy3d_module_bp6's compute_pf). BP8
! needs a genuinely 2-component (V2,V3) coupled friction system and 2D
! radial pore-pressure diffusion (module_pore_fluid_2d.f90) -- see derivs()
! below for the derivation.
!
! Mesh: assumes a mesh generated by example4/make_bp8_mesh.py, which is
! EXACTLY the frictional domain Omega_f = (-lf,lf) x (-lf,lf) (no locked
! buffer): a region with slip forced to zero for all time contributes zero
! elastic stress to its neighbors regardless of how far the mesh extends
! (a standard fact for boundary-integral crack/fault problems), so meshing
! only Omega_f gives the same answer as meshing Omega_f plus a locked
! surrounding buffer, at a fraction of the cost. See example4/README_BP8.md
! for the domain-independence check this assumption still deserves (per
! the benchmark's own suggestion to test more than one domain size).
!
! Input: parameter1.txt (see example4/parameter1.txt), and
!   NikkhooWalter2015/calc_nikkhoo_fs.f90's output (position.bin,
!   trigreen_{22,23,32,33}_<rank>.bin) -- must be generated with the SAME
!   -np as this driver is run with, since element ranges are assigned by
!   the identical (Nt_all, nprocs, myid) decomposition formula in both.
!
! Output (BP8 Section 4 formats, all under foldername/):
!   fltst_strk{+-}NNNdp{+-}NNN  - 9 station time series (11 columns)
!   global.dat                  - Vmax(t), moment rate(t)
!   {slip,shear_stress}_{2,3}_{strike,depth}.dat, pore_pressure_{strike,depth}.dat
!                                - 10 spatial profile files
!
! NOTE on field-name spelling: the benchmark PDF's extracted text renders
! compound field names with spaces ("slip 2", "shear stress 2"); every
! other SEAS benchmark (BP1-BP7) uses underscore_separated names in this
! exact file format ("slip_2", "shear_stress_2"), and the PDF's own field
! table lists these as single identifiers, not prose -- so this driver
! writes underscored names (BP8_FIELD_LIST below). If the actual upload
! server rejects this, it is a single string constant to change.
!===============================================================================

program bp8_main
  use mpi
  use bp8_module
  use pore_fluid_2d
  implicit none

  integer :: ierr, myid, size
  integer :: base_cells, extra_cells, local_cells, start_idx
  integer :: Nt_all
  integer, dimension(:), allocatable :: sendcounts, displs
  integer :: i, k, out_step_count

  real(DP), dimension(:), allocatable :: yt, dydt, yt_scale
  real(DP) :: t, dt_try, dt_did, dt_next, eps, next_out_time

  external :: derivs

  call MPI_Init(ierr)
  call MPI_COMM_RANK(MPI_COMM_WORLD, myid, ierr)
  call MPI_COMM_SIZE(MPI_COMM_WORLD, size, ierr)
  master_id = 0
  nprocs = size

  call read_parameters(myid)

  Nt_all = 2 * n_side * n_side

  base_cells = Nt_all / size
  extra_cells = mod(Nt_all, size)
  if (myid < extra_cells) then
    local_cells = base_cells + 1
    start_idx = myid * (base_cells + 1) + 1
  else
    local_cells = base_cells
    start_idx = extra_cells * (base_cells + 1) + (myid - extra_cells) * base_cells + 1
  end if
  my_start_idx = start_idx
  my_local_cells = local_cells

  allocate(sendcounts(0:size-1), displs(0:size-1))
  call MPI_Allgather(local_cells, 1, MPI_INTEGER, sendcounts, 1, MPI_INTEGER, MPI_COMM_WORLD, ierr)
  displs(0) = 0
  do i = 1, size - 1
    displs(i) = displs(i-1) + sendcounts(i-1)
  end do

  if (myid == master_id) then
    write(*,*) "=========================================="
    write(*,*) "BP8-QD-GS: Nt_all=", Nt_all, " ranks=", size
    write(*,*) "=========================================="
  end if

  allocate(K22(max(1,local_cells), Nt_all), K23(max(1,local_cells), Nt_all))
  allocate(K32(max(1,local_cells), Nt_all), K33(max(1,local_cells), Nt_all))
  allocate(cx2_all(Nt_all), cx3_all(Nt_all))

  call load_stiffness_and_positions(myid, local_cells, Nt_all)
  call pf_history_init(Nt_all, myid)

  ! Zone which LOCAL elements fall inside the true frictional domain
  ! Omega_f (|x2|<lf_fixed and |x3|<lf_fixed, both fixed at 400m by BP8
  ! Table 1) vs. outside it, where Eq. 13 forces V=0 identically -- this
  ! is what lets the mesh be bigger than Omega_f (e.g. for a domain-
  ! independence check) without silently giving every extra element
  ! rate-and-state friction. See derivs() and set_initial_conditions().
  allocate(is_active(max(1, local_cells)))
  do i = 1, local_cells
    k = start_idx + i - 1
    is_active(i) = (abs(cx2_all(k)) < lf_fixed) .and. (abs(cx3_all(k)) < lf_fixed)
  end do
  if (myid == master_id) then
    write(*,*) "Omega_f (lf_fixed=", lf_fixed, "m) active elements (this rank):", count(is_active), "/", local_cells
  end if

  ! State is (s2, s3, theta) per element -- 3 components, NOT 5. Slip rate
  ! is no longer integrated; it is solved from the force balance each time
  ! derivs() is called (see the derivation there).
  n_state = 3 * local_cells
  allocate(yt(n_state), dydt(n_state), yt_scale(n_state))
  allocate(Vsol2(max(1,local_cells)), Vsol3(max(1,local_cells)))
  allocate(tausol2(max(1,local_cells)), tausol3(max(1,local_cells)))
  allocate(Vguess(max(1,local_cells)))
  call set_initial_conditions(yt, local_cells)

  if (myid == master_id) call open_output_files()

  t = 0.0_DP
  dt_try = 100.0_DP
  eps = 1.0d-6
  next_out_time = 0.0_DP
  out_step_count = 0

  call derivs(myid, dydt, n_state, Nt_all, local_cells, t, yt, sendcounts, displs)
  call write_all_output(myid, t, yt, dydt, local_cells, Nt_all, sendcounts, displs)
  next_out_time = next_out_time + tint_out
  out_step_count = out_step_count + 1

  do while (t < tf_end)
    do i = 1, n_state
      yt_scale(i) = abs(yt(i)) + abs(dt_try * dydt(i)) + 1.0d-30
    end do

    if (t + dt_try > tf_end) dt_try = tf_end - t

    call rkqs(myid, yt, dydt, n_state, Nt_all, local_cells, t, dt_try, eps, yt_scale, &
             dt_did, dt_next, sendcounts, displs)

    call derivs(myid, dydt, n_state, Nt_all, local_cells, t, yt, sendcounts, displs)

    if (t >= next_out_time - 1.0d-6 .or. t >= tf_end - 1.0d-6) then
      call write_all_output(myid, t, yt, dydt, local_cells, Nt_all, sendcounts, displs)
      next_out_time = next_out_time + tint_out
      out_step_count = out_step_count + 1
    end if

    dt_try = dt_next
  end do

  if (myid == master_id) then
    call close_output_files()
    write(*,*) "BP8 run complete. t=", t, " output steps=", out_step_count
  end if

  call MPI_Finalize(ierr)

end program bp8_main


!===============================================================================
subroutine read_parameters(myid)
  use bp8_module
  implicit none
  integer, intent(in) :: myid

  open(12, file='./parameter1.txt', form='formatted', status='old')
  read(12,'(a)') foldername
  read(12,'(a)') stiffname
  read(12,*) n_side, dz_cell
  read(12,*) xmu, xnu, rho
  read(12,*) seff0, tauinit
  read(12,*) fric_a, fric_b, fric_Drs, fric_Vstar, fric_fstar
  read(12,*) Vinit, Vzero
  read(12,*) Q0inj, Lfwid, toff, Lgauss
  read(12,*) alpha_diff, beta_diff, phi_diff
  read(12,*) tf_end, tint_out
  close(12)

  cs = sqrt(xmu / rho)
  eta = 0.5_DP * xmu / cs
  lf_half = 0.5_DP * real(n_side, DP) * dz_cell

  if (lf_half < lf_fixed) then
    write(*,*) "ERROR: mesh half-domain (", lf_half, "m) is smaller than Omega_f (lf_fixed=", &
               lf_fixed, "m) -- the mesh must cover at least the true frictional domain."
    stop 1
  end if

  if (myid == 0) then
    write(*,*) "Parameters: n_side=", n_side, " dz=", dz_cell, " mesh_half_domain=", lf_half, &
                " Omega_f_half(fixed)=", lf_fixed
    write(*,*) "mu=", xmu, " eta=", eta, " seff0=", seff0, " tauinit=", tauinit
    write(*,*) "a=", fric_a, " b=", fric_b, " Drs=", fric_Drs
    write(*,*) "Q0=", Q0inj, " toff(hr)=", toff/3600.0_DP, " Lgauss=", Lgauss
    write(*,*) "alpha=", alpha_diff, " beta=", beta_diff, " phi=", phi_diff
    write(*,*) "tf(days)=", tf_end/86400.0_DP, " tint_out(s)=", tint_out
  end if
end subroutine read_parameters


!===============================================================================
! Loads position.bin (all Nt_all centroids, broadcast to every rank) and
! this rank's chunk of the four trigreen_*.bin stiffness files.
!===============================================================================
subroutine load_stiffness_and_positions(myid, local_cells, Nt_all)
  use mpi
  use bp8_module
  implicit none
  integer, intent(in) :: myid, local_cells, Nt_all
  real(DP) :: pos3(3)
  integer :: ii, ierr
  character(len=20) :: cT

  if (myid == 0) then
    open(21, file=trim(stiffname)//'position.bin', form='unformatted', access='stream', status='old')
    do ii = 1, Nt_all
      read(21) pos3
      cx2_all(ii) = pos3(1)
      cx3_all(ii) = pos3(2)
    end do
    close(21)
  end if
  call MPI_Bcast(cx2_all, Nt_all, MPI_Real8, 0, MPI_COMM_WORLD, ierr)
  call MPI_Bcast(cx3_all, Nt_all, MPI_Real8, 0, MPI_COMM_WORLD, ierr)

  write(cT,*) myid
  if (local_cells > 0) then
    open(22, file=trim(stiffname)//'trigreen_22_'//trim(adjustl(cT))//'.bin', &
        form='unformatted', access='stream', status='old')
    do ii = 1, local_cells
      read(22) K22(ii, :)
    end do
    close(22)

    open(23, file=trim(stiffname)//'trigreen_23_'//trim(adjustl(cT))//'.bin', &
        form='unformatted', access='stream', status='old')
    do ii = 1, local_cells
      read(23) K23(ii, :)
    end do
    close(23)

    open(24, file=trim(stiffname)//'trigreen_32_'//trim(adjustl(cT))//'.bin', &
        form='unformatted', access='stream', status='old')
    do ii = 1, local_cells
      read(24) K32(ii, :)
    end do
    close(24)

    open(25, file=trim(stiffname)//'trigreen_33_'//trim(adjustl(cT))//'.bin', &
        form='unformatted', access='stream', status='old')
    do ii = 1, local_cells
      read(25) K33(ii, :)
    end do
    close(25)
  end if
end subroutine load_stiffness_and_positions


!===============================================================================
! Precomputes pore pressure at every element centroid on an hourly time
! grid by advancing module_pore_fluid_2d's structured FD solve once (every
! rank does this redundantly -- deterministic given only global
! parameters, cheap relative to the mechanical time loop, and avoids a
! broadcast of the full (n_hours, Nt_all) history array).
!===============================================================================
subroutine pf_history_init(Nt_all, myid)
  use bp8_module
  use pore_fluid_2d
  implicit none
  integer, intent(in) :: Nt_all, myid
  integer, parameter :: NXY = 81
  real(DP) :: pgrid(NXY, NXY)
  real(DP) :: half, dxg, th
  integer :: ih, ii

  ! Fluid flow (BP8 Eq. 17-18) is confined to Omega_f itself, not whatever
  ! the mesh's own extent happens to be -- so this domain is lf_fixed
  ! (400m, fixed), never lf_half. With NXY=81 fixed too, dxg is always
  ! exactly 10m, matching the required profile-output node spacing
  ! regardless of the mesh's own cell size.
  half = lf_fixed
  dxg = 2.0_DP * half / real(NXY - 1, DP)
  dt_hist = 3600.0_DP
  n_hours_hist = int(ceiling(tf_end / dt_hist)) + 1
  allocate(p_hist(0:n_hours_hist, Nt_all))

  pgrid = 0.0_DP
  p_hist(0, :) = 0.0_DP
  th = 0.0_DP
  do ih = 1, n_hours_hist
    call pf2d_step(pgrid, NXY, NXY, dxg, -half, -half, th, dt_hist, &
                   alpha_diff, beta_diff, phi_diff, Q0inj/Lfwid, toff, Lgauss)
    th = th + dt_hist
    do ii = 1, Nt_all
      p_hist(ih, ii) = pf2d_interpolate(pgrid, NXY, NXY, dxg, -half, -half, cx2_all(ii), cx3_all(ii))
    end do
  end do

  if (myid == 0) write(*,*) "Pore pressure history precomputed:", n_hours_hist, "hourly snapshots"
end subroutine pf_history_init


!===============================================================================
! Linear-in-time lookup of pressure and its time derivative at global
! element index k from the hourly-snapshot history.
!===============================================================================
subroutine pf_lookup(t_query, k, p_val, dpdt_val)
  use bp8_module
  implicit none
  real(DP), intent(in) :: t_query
  integer, intent(in) :: k
  real(DP), intent(out) :: p_val, dpdt_val
  integer :: ih0
  real(DP) :: frac

  ih0 = max(0, min(n_hours_hist - 1, int(t_query / dt_hist)))
  frac = (t_query - real(ih0, DP) * dt_hist) / dt_hist
  frac = max(0.0_DP, min(1.0_DP, frac))
  p_val = (1.0_DP - frac) * p_hist(ih0, k) + frac * p_hist(ih0 + 1, k)
  dpdt_val = (p_hist(ih0 + 1, k) - p_hist(ih0, k)) / dt_hist
end subroutine pf_lookup


!===============================================================================
subroutine set_initial_conditions(yt, local_cells)
  use bp8_module
  implicit none
  integer, intent(in) :: local_cells
  real(DP), intent(out) :: yt(3*local_cells)
  real(DP) :: Vmag0, f_init, theta_init, X0
  integer :: i

  Vmag0 = sqrt(Vinit**2 + Vzero**2)
  f_init = tauinit / seff0
  X0 = sinh(f_init / fric_a)
  ! Invert Eq. (12) for theta at t=0 given V=Vmag0, f=f_init (see derivs()
  ! for the friction law in the same form).
  theta_init = (fric_Drs / fric_Vstar) * &
               exp((fric_a * log(2.0_DP * fric_Vstar * X0 / Vmag0) - fric_fstar) / fric_b)

  ! Fixed reference traction (Eq. 29): tau0 = tauinit * V/|V| at t=0.
  tau0_2 = tauinit * Vinit / Vmag0
  tau0_3 = tauinit * Vzero / Vmag0

  ! State: (s2, s3, theta). Slip starts at zero everywhere (Eq. 26) --
  ! including outside Omega_f, where it stays zero for all time (Eq. 13),
  ! so no special-casing is needed here or in derivs(): a locked element's
  ! stress follows from the global slip field like any other element's.
  do i = 1, local_cells
    yt(3*i-2) = 0.0_DP      ! s2
    yt(3*i-1) = 0.0_DP      ! s3
    yt(3*i)   = theta_init  ! theta (unused where locked)
    Vguess(i) = Vmag0       ! Newton warm start
  end do
end subroutine set_initial_conditions


!===============================================================================
! Solves the scalar force balance for the slip-rate magnitude V > 0:
!
!     G(V) = eta*V + sigma_bar*f(V,theta) - |tau_el| = 0
!
! where |tau_el| = |tau0 + Dtau| is the magnitude of the elastic traction
! (BP8 Eq. 8 rearranged, see derivs() for why the direction decouples).
!
! G is strictly increasing in V (both eta*V and f are), so the root is
! unique and Newton is globally convergent from any positive start. The
! iteration runs on W = ln V, since V ranges over ~20 decades; there
! dG/dW = eta*V + sigma_bar*a*X/sqrt(1+X^2) stays O(sigma_bar*a), which is
! well conditioned.
!
! X = (V/2V*)exp((f* + b ln(V* theta/Drs))/a) can overflow double precision
! for large V or theta, so it is formed in logs and the large-X limits
! asinh(X) -> ln(2X) and X/sqrt(1+X^2) -> 1 are used past ln X > 30.
!===============================================================================
subroutine solve_slip_rate(tau_mag, sigma_bar, theta, V_start, V, n_iter, resid)
  use bp8_module
  implicit none
  real(DP), intent(in) :: tau_mag, sigma_bar, theta, V_start
  real(DP), intent(out) :: V, resid
  integer, intent(out) :: n_iter

  real(DP) :: W, dW, lnX, X, f_coef, dfdV_term, G, dGdW, sq
  real(DP), parameter :: LNX_BIG = 30.0_DP
  integer :: it

  W = log(max(V_start, 1.0d-25))

  do it = 1, 100
    lnX = log(max(exp(W), 1.0d-300) / (2.0_DP * fric_Vstar)) &
          + (fric_fstar + fric_b * log(fric_Vstar * theta / fric_Drs)) / fric_a

    if (lnX > LNX_BIG) then
      ! asinh(X) = ln(2X) to double precision here; X/sqrt(1+X^2) = 1
      f_coef = fric_a * (log(2.0_DP) + lnX)
      dfdV_term = fric_a
    else
      X = exp(lnX)
      sq = sqrt(1.0_DP + X**2)
      f_coef = fric_a * log(X + sq)
      dfdV_term = fric_a * X / sq
    end if

    G = eta * exp(W) + sigma_bar * f_coef - tau_mag
    dGdW = eta * exp(W) + sigma_bar * dfdV_term

    dW = -G / dGdW
    ! Cap the step: keeps the first iterations sane when the warm start is
    ! many decades off (e.g. right after a rapid acceleration).
    dW = max(-5.0_DP, min(5.0_DP, dW))
    W = W + dW
    n_iter = it
    if (abs(dW) < 1.0d-13) exit
  end do

  V = exp(W)
  resid = abs(G) / max(abs(tau_mag), 1.0_DP)
end subroutine solve_slip_rate


!===============================================================================
! Right-hand side of the ODE system for (s2, s3, theta) per element.
!
! ALGEBRAIC (Newton) FORMULATION. Rather than differentiating the force
! balance to get an explicit dV/dt (the approach in 3dtri_BP5.f90, and in
! earlier versions of this file), the balance is solved directly for V at
! every stage. Slip rate is therefore a function of the state, not part of
! it, and the constraint holds to Newton tolerance by construction at
! every RK stage -- it cannot drift, and no partial derivative of f with
! respect to theta ever enters. That matters here: an earlier derivative-
! form version had a spurious factor of `a` in df/dtheta which made the
! state-weakening feedback 62.5x too weak, and because the resulting ODE
! was no longer the exact derivative of the balance, the error showed up
! as a ~22% force-balance violation that tightening the integrator
! tolerance could not reduce. This formulation removes that whole class of
! bug: only f itself and df/dV are needed, and df/dV is exercised directly
! by the Newton residual.
!
! Force balance (BP8 Eq. 8-10), with tau_el_j = tau0_j + Dtau_j the elastic
! traction and sigma_bar = seff0 - p(t):
!
!     tau_el_j - eta*V_j = sigma_bar * f(V,theta) * V_j/V,   j=2,3
!
! Substituting V_j = V*e_j and collecting:
!
!     tau_el_j = e_j * ( eta*V + sigma_bar*f(V,theta) )
!
! The bracket is a positive scalar, so **e_j is parallel to tau_el_j**: the
! slip direction is set by the traction direction, and the magnitude
! follows from the scalar equation
!
!     eta*V + sigma_bar*f(V,theta) = |tau_el|
!
! solved by solve_slip_rate(). This exact decoupling of direction from
! magnitude is what makes the 2x2 system of the old formulation
! unnecessary.
!
! Dtau_j = K_j2 (dot) s2_all + K_j3 (dot) s3_all -- the stiffness applied
! to SLIP (not slip rate, as in the derivative form; K is a constant linear
! operator so both are equivalent, but using slip directly is what removes
! the possibility of the integrated stress drifting away from K.s).
! There is no Vpl term: BP8 has no far-field plate loading. K22/K23/K32/K33
! are read in MPa/m (MPA_TO_PA in bp8_module) and scaled to Pa/m here.
!
! Outside Omega_f (Eq. 13) slip is identically zero for all time, so those
! elements simply keep ds/dt = 0; their traction still evolves through
! coupling to the slipping region and is reported normally.
!===============================================================================
subroutine derivs(myid, dydt, nv, Nt_all, Nt, t, yt, sendcounts, displs)
  use mpi
  use bp8_module
  implicit none
  integer, intent(in) :: myid, nv, Nt_all, Nt
  real(DP), intent(in) :: t, yt(nv)
  real(DP), intent(out) :: dydt(nv)
  integer, intent(in) :: sendcounts(0:*), displs(0:*)

  real(DP) :: s2_local(Nt), s3_local(Nt)
  real(DP), allocatable :: s2_all(:), s3_all(:)
  real(DP) :: tau2_el, tau3_el, tau_mag
  real(DP) :: V, theta, p_val, dpdt_val, sigma_bar, resid
  integer :: i, k, ierr, nit

  allocate(s2_all(Nt_all), s3_all(Nt_all))

  do i = 1, Nt
    s2_local(i) = yt(3*i-2)
    s3_local(i) = yt(3*i-1)
  end do

  call MPI_Allgatherv(s2_local, Nt, MPI_Real8, s2_all, sendcounts, displs, MPI_Real8, MPI_COMM_WORLD, ierr)
  call MPI_Allgatherv(s3_local, Nt, MPI_Real8, s3_all, sendcounts, displs, MPI_Real8, MPI_COMM_WORLD, ierr)

  do i = 1, Nt
    k = displs(myid) + i   ! global index (1-based) of local element i

    ! Elastic traction from the current slip field (Pa).
    tau2_el = tau0_2 + MPA_TO_PA * (dot_product(K22(i, :), s2_all) + dot_product(K23(i, :), s3_all))
    tau3_el = tau0_3 + MPA_TO_PA * (dot_product(K32(i, :), s2_all) + dot_product(K33(i, :), s3_all))

    if (.not. is_active(i)) then
      ! Locked (Eq. 13): V = 0 for all time. tau = tau0 + Dtau with no
      ! radiation-damping term.
      dydt(3*i-2) = 0.0_DP
      dydt(3*i-1) = 0.0_DP
      dydt(3*i)   = 0.0_DP
      Vsol2(i) = 0.0_DP
      Vsol3(i) = 0.0_DP
      tausol2(i) = tau2_el
      tausol3(i) = tau3_el
      cycle
    end if

    call pf_lookup(t, k, p_val, dpdt_val)
    sigma_bar = seff0 - p_val
    theta = max(yt(3*i), 1.0d-12)

    tau_mag = sqrt(tau2_el**2 + tau3_el**2)

    call solve_slip_rate(tau_mag, sigma_bar, theta, Vguess(i), V, nit, resid)
    Vguess(i) = V
    newton_max_resid = max(newton_max_resid, resid)
    newton_max_iter = max(newton_max_iter, nit)

    ! Slip direction = traction direction (see header).
    Vsol2(i) = V * tau2_el / tau_mag
    Vsol3(i) = V * tau3_el / tau_mag

    ! Reported fault shear stress, Eq. 8: tau = tau0 + Dtau - eta*V.
    tausol2(i) = tau2_el - eta * Vsol2(i)
    tausol3(i) = tau3_el - eta * Vsol3(i)

    dydt(3*i-2) = Vsol2(i)                          ! ds2/dt
    dydt(3*i-1) = Vsol3(i)                          ! ds3/dt
    dydt(3*i)   = 1.0_DP - V * theta / fric_Drs     ! aging law, Eq. 11
  end do

  deallocate(s2_all, s3_all)
end subroutine derivs


!===============================================================================
! Cash-Karp adaptive-step RK integrator, copied from src/3dtri_BP5.f90 with
! the module dependency switched from phy3d_module_bp6 to bp8_module (both
! expose only 'nprocs', which is all rkqs/rkck need) and the extra
! z_all/p arguments (BP5's mesh-position bookkeeping, unused by derivs
! here) dropped since bp8_module's derivs looks up positions via its own
! module state instead.
!===============================================================================
subroutine rkqs(myid, y, dydx, n, Nt_all, Nt, x, htry, eps, yscal, hdid, hnext, sendcounts, displs)
  use mpi
  use bp8_module, only: nprocs, DP
  implicit none
  integer :: n, i, NMAX, Nt, Nt_all
  real(DP) :: eps, hdid, hnext, htry, x
  real(DP) :: dydx(n), y(n), yscal(n)
  integer :: sendcounts(0:*), displs(0:*)
  external :: derivs
  real(DP) :: errmax, errmax1, h, htemp, xnew, errmax_all(nprocs)
  real(DP), dimension(:), allocatable :: yerr, ytemp
  real(DP), parameter :: SAFETY=0.9, PGROW=-.2, PSHRNK=-.25, ERRCON=1.89e-4

  integer :: ierr, myid, master
  master = 0

  nmax = n
  h = htry
  allocate(yerr(nmax), ytemp(nmax))

1 call rkck(myid, dydx, h, n, Nt_all, Nt, y, yerr, ytemp, x, sendcounts, displs)

  errmax = 0.
  do i = 1, nmax
    errmax = max(errmax, dabs(yerr(i) / yscal(i)))
  end do
  errmax = errmax / eps

  call MPI_Allreduce(errmax, errmax1, 1, MPI_Real8, MPI_MAX, MPI_COMM_WORLD, ierr)

  if (errmax1 .gt. 1.) then
    htemp = SAFETY * h * (errmax1**PSHRNK)
    h = dsign(max(dabs(htemp), 0.1*dabs(h)), h)
    xnew = x + h
    if (xnew .eq. x) write(*,*) 'stepsize underflow in rkqs'
    goto 1
  else
    if (errmax1 .gt. ERRCON) then
      hnext = SAFETY * h * (errmax1**PGROW)
    else
      hnext = 5. * h
    end if
    hdid = h
    x = x + h
    do i = 1, nmax
      y(i) = ytemp(i)
    end do
  end if

  deallocate(yerr, ytemp)
end subroutine rkqs


subroutine rkck(myid, dydx, h, n, Nt_all, Nt, y, yerr, yout, x, sendcounts, displs)
  use bp8_module, only: DP
  implicit none
  integer :: n, i, NMAX, myid, Nt_all, Nt
  integer :: sendcounts(0:*), displs(0:*)
  external :: derivs
  real(DP) :: h, x, dydx(n), y(n), yerr(n), yout(n)
  real(DP), dimension(:), allocatable :: ak2, ak3, ak4, ak5, ak6, ytemp
  real(DP), parameter :: A2=.2,A3=.3,A4=.6,A5=1.,A6=.875, &
       B21=.2,B31=3./40.,B32=9./40.,B41=.3,&
       B42=-.9,B43=1.2,B51=-11./54.,B52=2.5, &
       B53=-70./27.,B54=35./27., B61=1631./55296., &
       B62=175./512.,B63=575./13824.,B64=44275./110592., &
       B65=253./4096.,C1=37./378., C3=250./621.,  &
       C4=125./594.,C6=512./1771.,DC1=C1-2825./27648., &
       DC3=C3-18575./48384.,DC4=C4-13525./55296.,  &
       DC5=-277./14336.,DC6=C6-.25

  nmax = n
  allocate(ak2(nmax), ak3(NMAX), ak4(NMAX), ak5(NMAX), ak6(NMAX), ytemp(NMAX))

  do i = 1, n
    ytemp(i) = y(i) + B21*h*dydx(i)
  end do
  call derivs(myid, ak2, n, Nt_all, Nt, x+A2*h, ytemp, sendcounts, displs)

  do i = 1, n
    ytemp(i) = y(i) + h*(B31*dydx(i)+B32*ak2(i))
  end do
  call derivs(myid, ak3, n, Nt_all, Nt, x+A3*h, ytemp, sendcounts, displs)

  do i = 1, n
    ytemp(i) = y(i) + h*(B41*dydx(i)+B42*ak2(i)+B43*ak3(i))
  end do
  call derivs(myid, ak4, n, Nt_all, Nt, x+A4*h, ytemp, sendcounts, displs)

  do i = 1, n
    ytemp(i) = y(i) + h*(B51*dydx(i)+B52*ak2(i)+B53*ak3(i)+B54*ak4(i))
  end do
  call derivs(myid, ak5, n, Nt_all, Nt, x+A5*h, ytemp, sendcounts, displs)

  do i = 1, n
    ytemp(i) = y(i) + h*(B61*dydx(i)+B62*ak2(i)+B63*ak3(i)+B64*ak4(i)+B65*ak5(i))
  end do
  call derivs(myid, ak6, n, Nt_all, Nt, x+A6*h, ytemp, sendcounts, displs)

  do i = 1, n
    yout(i) = y(i) + h*(C1*dydx(i)+C3*ak3(i)+C4*ak4(i)+C6*ak6(i))
  end do

  do i = 1, n
    yerr(i) = h*(DC1*dydx(i)+DC3*ak3(i)+DC4*ak4(i)+DC5*ak5(i)+DC6*ak6(i))
  end do

  deallocate(ak2, ak3, ak4, ak5, ak6, ytemp)
end subroutine rkck


!===============================================================================
! Given a global element index k (1-based), recover its (i,j) cell and
! triangle-half, using example4/make_bp8_mesh.py's known face ordering:
! cell (i,j) (0-based, i=x2 index, j=x3 index) emits faces
! 2*(j*n_side+i)+1 and 2*(j*n_side+i)+2 (1-based). This lets the driver
! locate neighboring/query cells arithmetically without re-parsing the GTS
! mesh file.
!===============================================================================
subroutine k_to_ij(k, n_side, i0, j0)
  implicit none
  integer, intent(in) :: k, n_side
  integer, intent(out) :: i0, j0
  integer :: cell0

  cell0 = (k - 1) / 2
  i0 = mod(cell0, n_side)
  j0 = cell0 / n_side
end subroutine k_to_ij

subroutine ij_to_k(i0, j0, n_side, k1, k2)
  implicit none
  integer, intent(in) :: i0, j0, n_side
  integer, intent(out) :: k1, k2
  integer :: cell0

  cell0 = j0 * n_side + i0
  k1 = 2 * cell0 + 1
  k2 = k1 + 1
end subroutine ij_to_k

!===============================================================================
! Builds a cell-centered (n_side x n_side) field from a per-triangle field
! by averaging each cell's 2 triangles.
!===============================================================================
subroutine build_cell_field(field_tri, Nt_all, n_side, field_cell)
  use bp8_module, only: DP
  implicit none
  integer, intent(in) :: Nt_all, n_side
  real(DP), intent(in) :: field_tri(Nt_all)
  real(DP), intent(out) :: field_cell(n_side, n_side)
  integer :: i0, j0, k1, k2

  do j0 = 0, n_side - 1
    do i0 = 0, n_side - 1
      call ij_to_k(i0, j0, n_side, k1, k2)
      field_cell(i0+1, j0+1) = 0.5_DP * (field_tri(k1) + field_tri(k2))
    end do
  end do
end subroutine build_cell_field

!===============================================================================
! Bilinear interpolation of a cell-centered field (as built by
! build_cell_field) at query point (xq,yq). Cell (i,j)'s center sits at
! x2min+(i+0.5)*dz, x3min+(j+0.5)*dz; clamps to the outermost cell centers
! rather than extrapolating. This is symmetric under x2->-x2 (unlike a
! "pick the nearest single cell" rule, which is NOT mirror-symmetric for
! query points exactly on a cell boundary -- and every BP8 output node is
! exactly on a cell boundary, since dz_cell equals the required node
! spacing. An earlier version of this file used the nearest-cell rule and
! produced visibly asymmetric profile output for a centered symmetric
! source; this bilinear version was verified to fix it.)
!===============================================================================
real(8) function bilinear_cell(field_cell, n_side, dz, half, xq, yq) result(val)
  use bp8_module, only: DP
  implicit none
  integer, intent(in) :: n_side
  real(DP), intent(in) :: field_cell(n_side, n_side), dz, half, xq, yq
  real(DP) :: fx, fy, tx, ty
  integer :: i0, j0, i1, j1

  fx = (xq - (-half + 0.5_DP*dz)) / dz
  fy = (yq - (-half + 0.5_DP*dz)) / dz

  i0 = max(1, min(n_side - 1, int(floor(fx)) + 1))
  j0 = max(1, min(n_side - 1, int(floor(fy)) + 1))
  i1 = i0 + 1
  j1 = j0 + 1

  tx = max(0.0_DP, min(1.0_DP, fx - real(i0 - 1, DP)))
  ty = max(0.0_DP, min(1.0_DP, fy - real(j0 - 1, DP)))

  val = (1.0_DP-tx)*(1.0_DP-ty)*field_cell(i0,j0) + tx*(1.0_DP-ty)*field_cell(i1,j0) + &
        (1.0_DP-tx)*ty*field_cell(i0,j1) + tx*ty*field_cell(i1,j1)
end function bilinear_cell


!===============================================================================
! Output setup: opens the 9 station files, global.dat, and 10 profile
! files, writing headers and (for profile files) the first "0 0 <nodes>"
! row. All under foldername/.
!
! Field-list line uses underscored names (slip_2, shear_stress_2, ...);
! see the note at the top of this file on why.
!===============================================================================
subroutine open_output_files()
  use bp8_module
  implicit none
  integer :: is
  character(len=256) :: fn
  character(len=32) :: stnames(9)
  real(DP) :: stx2(9), stx3(9)
  character(len=*), parameter :: FIELDS_TS = &
    't slip_2 slip_3 slip_rate_2 slip_rate_3 shear_stress_2 shear_stress_3 pore_pressure darcy_vel_2 darcy_vel_3 state'
  character(len=*), parameter :: FIELDS_GLOBAL = 't max_slip_rate moment_rate'

  stnames = [character(len=32) :: 'fltst_strk+000dp+000', 'fltst_strk-200dp+000', &
             'fltst_strk+000dp+200', 'fltst_strk+200dp+000', 'fltst_strk+000dp-200', &
             'fltst_strk-200dp-200', 'fltst_strk-200dp+200', 'fltst_strk+200dp-200', &
             'fltst_strk+200dp+200']
  stx2 = [0.0_DP, -200.0_DP, 0.0_DP, 200.0_DP, 0.0_DP, -200.0_DP, -200.0_DP, 200.0_DP, 200.0_DP]
  stx3 = [0.0_DP, 0.0_DP, 200.0_DP, 0.0_DP, -200.0_DP, -200.0_DP, 200.0_DP, -200.0_DP, 200.0_DP]

  do is = 1, 9
    fn = trim(foldername) // trim(stnames(is))
    open(300 + is, file=trim(fn), status='unknown')
    write(300+is,'(A)') '# This is the file header:'
    write(300+is,'(A)') '# problem=SEAS Benchmark BP8-QD-GS'
    write(300+is,'(A)') '# code=TriBIE'
    write(300+is,'(A)') '# modeler=D.Li'
    write(300+is,'(A,F6.1,A)') '# element_size=', dz_cell, ' m'
    write(300+is,'(A,F8.1,A,F8.1,A)') '# location: x2=', stx2(is), ' m, x3=', stx3(is), ' m'
    write(300+is,'(A)') '# Column #1 = Time (s)'
    write(300+is,'(A)') '# Column #2 = Slip_2 (m)'
    write(300+is,'(A)') '# Column #3 = Slip_3 (m)'
    write(300+is,'(A)') '# Column #4 = Slip_rate_2 (log10 m/s)'
    write(300+is,'(A)') '# Column #5 = Slip_rate_3 (log10 m/s)'
    write(300+is,'(A)') '# Column #6 = Shear_stress_2 (MPa)'
    write(300+is,'(A)') '# Column #7 = Shear_stress_3 (MPa)'
    write(300+is,'(A)') '# Column #8 = Pore_pressure (MPa)'
    write(300+is,'(A)') '# Column #9 = Darcy_velocity_2 (m/s)'
    write(300+is,'(A)') '# Column #10 = Darcy_velocity_3 (m/s)'
    write(300+is,'(A)') '# Column #11 = State (log10 s)'
    write(300+is,'(A)') '# The line below lists the names of the data fields'
    write(300+is,'(A)') FIELDS_TS
    write(300+is,'(A)') '# Below is the time-series data.'
  end do

  open(400, file=trim(foldername)//'global.dat', status='unknown')
  write(400,'(A)') '# This is the file header:'
  write(400,'(A)') '# problem=SEAS Benchmark BP8-QD-GS'
  write(400,'(A)') '# code=TriBIE'
  write(400,'(A)') '# modeler=D.Li'
  write(400,'(A)') '# location=frictional domain'
  write(400,'(A)') '# Column #1 = Time (s)'
  write(400,'(A)') '# Column #2 = Max_slip_rate (log10 m/s)'
  write(400,'(A)') '# Column #3 = Moment_rate (N.m/s)'
  write(400,'(A)') '# The line below lists the names of the data fields'
  write(400,'(A)') FIELDS_GLOBAL
  write(400,'(A)') '# Below is the time-series data.'

  ! Profile files: slip_{2,3}_{strike,depth}.dat, shear_stress_{2,3}_{strike,depth}.dat,
  ! pore_pressure_{strike,depth}.dat
  call open_one_profile(410, 'slip_2_strike.dat', 'x2', 'slip_2')
  call open_one_profile(411, 'slip_2_depth.dat', 'x3', 'slip_2')
  call open_one_profile(412, 'slip_3_strike.dat', 'x2', 'slip_3')
  call open_one_profile(413, 'slip_3_depth.dat', 'x3', 'slip_3')
  call open_one_profile(414, 'shear_stress_2_strike.dat', 'x2', 'shear_stress_2')
  call open_one_profile(415, 'shear_stress_2_depth.dat', 'x3', 'shear_stress_2')
  call open_one_profile(416, 'shear_stress_3_strike.dat', 'x2', 'shear_stress_3')
  call open_one_profile(417, 'shear_stress_3_depth.dat', 'x3', 'shear_stress_3')
  call open_one_profile(418, 'pore_pressure_strike.dat', 'x2', 'pore_pressure')
  call open_one_profile(419, 'pore_pressure_depth.dat', 'x3', 'pore_pressure')

end subroutine open_output_files


subroutine open_one_profile(unit_no, fname, axis_name, var_name)
  use bp8_module
  implicit none
  integer, intent(in) :: unit_no
  character(len=*), intent(in) :: fname, axis_name, var_name
  integer :: i
  character(len=32) :: fmt_str

  open(unit_no, file=trim(foldername)//trim(fname), status='unknown')
  write(unit_no,'(A)') '# This is the file header:'
  write(unit_no,'(A)') '# problem=SEAS Benchmark BP8-QD-GS'
  write(unit_no,'(A)') '# author=D.Li'
  write(unit_no,'(A)') '# code=TriBIE'
  write(unit_no,'(A,F6.1,A)') '# element_size=', dz_cell, ' m'
  write(unit_no,'(A)') '# Row #1 = '//trim(axis_name)//' (m), two zeros first'
  write(unit_no,'(A)') '# Column #1 = Time (s)'
  write(unit_no,'(A)') '# Column #2 = Max_slip_rate (log10 m/s)'
  write(unit_no,'(A)') '# Columns #3-83 = '//trim(var_name)//' at each node'
  write(unit_no,'(A,F6.1,A,F6.1,A,F6.1,A,F6.1,A)') '# Computational domain (Omega_f, fixed): -', lf_fixed, &
      'm < x2 < ', lf_fixed, ' m, -', lf_fixed, ' m < x3 < ', lf_fixed, ' m'
  write(unit_no,'(A)') '# The line below lists the names of the data fields'
  write(unit_no,'(A)') trim(axis_name)
  write(unit_no,'(A)') 't'
  write(unit_no,'(A)') 'max_slip_rate'
  write(unit_no,'(A)') trim(var_name)
  write(unit_no,'(A)') '# Here are the data'

  ! Fixed 10m-spaced nodes from -400 to 400 (BP8 Section 4.3), regardless
  ! of the mesh's own resolution/domain size -- see node_dz_fixed/
  ! n_nodes_fixed/lf_fixed in bp8_module.f90.
  write(fmt_str,'(A,I0,A)') '(2E22.14,', n_nodes_fixed, 'E15.7)'
  write(unit_no,fmt_str) 0.0_DP, 0.0_DP, &
      (-lf_fixed + real(i-1,DP)*node_dz_fixed, i=1,n_nodes_fixed)
end subroutine open_one_profile


subroutine close_output_files()
  implicit none
  integer :: is
  do is = 1, 9
    close(300 + is)
  end do
  close(400)
  close(410); close(411); close(412); close(413); close(414)
  close(415); close(416); close(417); close(418); close(419)
end subroutine close_output_files


!===============================================================================
! Gathers the full state to master, computes derived fields (shear stress,
! pore pressure, Darcy velocity, log10 slip-rate/state), and writes one
! time-step's worth of data to every open output file. Called at each
! scheduled output time (see the tint_out trigger in the main program).
!===============================================================================
subroutine write_all_output(myid, t, yt, dydt, local_cells, Nt_all, sendcounts, displs)
  use mpi
  use bp8_module
  implicit none
  integer, intent(in) :: myid, local_cells, Nt_all
  real(DP), intent(in) :: t, yt(3*local_cells), dydt(3*local_cells)
  integer, intent(in) :: sendcounts(0:*), displs(0:*)

  real(DP), allocatable :: s2l(:), s3l(:), thl(:)
  real(DP), allocatable :: s2a(:), s3a(:), V2a(:), V3a(:), tha(:)
  real(DP), allocatable :: tau2a(:), tau3a(:), pa(:), dpdta(:), q2a(:), q3a(:)
  integer :: i, k, ierr
  real(DP) :: Vmax, moment_rate, Vmag
  real(DP) :: half, dz, gmax_resid
  integer :: gmax_iter

  allocate(s2l(local_cells), s3l(local_cells), thl(local_cells))
  do i = 1, local_cells
    s2l(i) = yt(3*i-2); s3l(i) = yt(3*i-1); thl(i) = yt(3*i)
  end do

  if (myid == 0) then
    allocate(s2a(Nt_all), s3a(Nt_all), V2a(Nt_all), V3a(Nt_all), tha(Nt_all))
    allocate(tau2a(Nt_all), tau3a(Nt_all), pa(Nt_all), dpdta(Nt_all), q2a(Nt_all), q3a(Nt_all))
  else
    allocate(s2a(1), s3a(1), V2a(1), V3a(1), tha(1))
    allocate(tau2a(1), tau3a(1), pa(1), dpdta(1), q2a(1), q3a(1))
  end if

  ! Slip rate and traction come straight from derivs()'s force-balance
  ! solve (module arrays Vsol*/tausol*), which the main loop has just
  ! evaluated at this accepted state -- no need to reconstruct the
  ! friction law here, and no possibility of the output disagreeing with
  ! what the solver actually used.
  call MPI_Gatherv(s2l, local_cells, MPI_Real8, s2a, sendcounts, displs, MPI_Real8, 0, MPI_COMM_WORLD, ierr)
  call MPI_Gatherv(s3l, local_cells, MPI_Real8, s3a, sendcounts, displs, MPI_Real8, 0, MPI_COMM_WORLD, ierr)
  call MPI_Gatherv(thl, local_cells, MPI_Real8, tha, sendcounts, displs, MPI_Real8, 0, MPI_COMM_WORLD, ierr)
  call MPI_Gatherv(Vsol2, local_cells, MPI_Real8, V2a, sendcounts, displs, MPI_Real8, 0, MPI_COMM_WORLD, ierr)
  call MPI_Gatherv(Vsol3, local_cells, MPI_Real8, V3a, sendcounts, displs, MPI_Real8, 0, MPI_COMM_WORLD, ierr)
  call MPI_Gatherv(tausol2, local_cells, MPI_Real8, tau2a, sendcounts, displs, MPI_Real8, 0, MPI_COMM_WORLD, ierr)
  call MPI_Gatherv(tausol3, local_cells, MPI_Real8, tau3a, sendcounts, displs, MPI_Real8, 0, MPI_COMM_WORLD, ierr)

  ! Monitor the force-balance solve: this replaces the drift check the
  ! derivative formulation needed, and should stay at round-off.
  call MPI_Reduce(newton_max_resid, gmax_resid, 1, MPI_Real8, MPI_MAX, 0, MPI_COMM_WORLD, ierr)
  call MPI_Reduce(newton_max_iter, gmax_iter, 1, MPI_INTEGER, MPI_MAX, 0, MPI_COMM_WORLD, ierr)
  newton_max_resid = 0.0_DP
  newton_max_iter = 0

  if (myid /= 0) then
    deallocate(s2l, s3l, thl)
    deallocate(s2a, s3a, V2a, V3a, tha, tau2a, tau3a, pa, dpdta, q2a, q3a)
    return
  end if

  if (gmax_resid > 1.0d-8) then
    write(*,'(A,E12.4,A,I4,A,E14.6)') ' WARNING: force-balance residual ', gmax_resid, &
        ' (max Newton iters ', gmax_iter, ') at t=', t
  end if

  half = lf_half
  dz = dz_cell

  do k = 1, Nt_all
    call pf_lookup(t, k, pa(k), dpdta(k))

    ! Darcy velocity via central finite difference of the pressure history
    ! at neighboring elements (Eq. 16): q_j = -(k/eta)*dp/dx_j, and
    ! k/eta = alpha*beta*phi (since alpha=k/(phi*beta*eta)).
    call darcy_component(t, k, 2, q2a(k))
    call darcy_component(t, k, 3, q3a(k))
  end do

  ! Locked elements are physically V=0, so they contribute nothing here.
  Vmax = 0.0_DP
  moment_rate = 0.0_DP
  do k = 1, Nt_all
    if (abs(cx2_all(k)) >= lf_fixed .or. abs(cx3_all(k)) >= lf_fixed) cycle
    Vmag = sqrt(V2a(k)**2 + V3a(k)**2)
    Vmax = max(Vmax, Vmag)
    moment_rate = moment_rate + xmu * Vmag * (0.5_DP * dz**2)
  end do

  ! --- station files ---
  block
    real(DP) :: stx2(9), stx3(9)
    integer :: is2
    stx2 = [0.0_DP, -200.0_DP, 0.0_DP, 200.0_DP, 0.0_DP, -200.0_DP, -200.0_DP, 200.0_DP, 200.0_DP]
    stx3 = [0.0_DP, 0.0_DP, 200.0_DP, 0.0_DP, -200.0_DP, -200.0_DP, 200.0_DP, -200.0_DP, 200.0_DP]
    do is2 = 1, 9
      call write_station_row(300+is2, t, stx2(is2), stx3(is2), n_side, dz, half, &
          s2a, s3a, V2a, V3a, tau2a, tau3a, pa, q2a, q3a, tha, Nt_all)
    end do
  end block

  ! --- global.dat ---
  write(400,'(3E15.7)') t, log10(max(Vmax,1.0d-20)), moment_rate

  ! --- profile files (strike: x3=0 line; depth: x2=0 line) ---
  call write_profile_row(410, t, Vmax, 'x2', s2a,   n_side, dz, half, Nt_all)
  call write_profile_row(411, t, Vmax, 'x3', s2a,   n_side, dz, half, Nt_all)
  call write_profile_row(412, t, Vmax, 'x2', s3a,   n_side, dz, half, Nt_all)
  call write_profile_row(413, t, Vmax, 'x3', s3a,   n_side, dz, half, Nt_all)
  call write_profile_row(414, t, Vmax, 'x2', tau2a, n_side, dz, half, Nt_all)
  call write_profile_row(415, t, Vmax, 'x3', tau2a, n_side, dz, half, Nt_all)
  call write_profile_row(416, t, Vmax, 'x2', tau3a, n_side, dz, half, Nt_all)
  call write_profile_row(417, t, Vmax, 'x3', tau3a, n_side, dz, half, Nt_all)
  call write_profile_row(418, t, Vmax, 'x2', pa,    n_side, dz, half, Nt_all)
  call write_profile_row(419, t, Vmax, 'x3', pa,    n_side, dz, half, Nt_all)

  ! Flush every output file after each step: this is a multi-day run with
  ! no checkpointing, so an interrupted/killed/preempted job should not
  ! lose output that the code already "wrote" but the OS never persisted.
  ! (Small files like global.dat can otherwise sit at 0 bytes for hours --
  ! confirmed during testing: killing an in-progress run left it empty
  ! even though station/profile files, which cross the buffer threshold
  ! sooner due to higher per-step byte volume, already showed data.)
  block
    integer :: fu
    do fu = 301, 309
      flush(fu)
    end do
    flush(400)
    do fu = 410, 419
      flush(fu)
    end do
  end block

  deallocate(s2l, s3l, thl)
  deallocate(s2a, s3a, V2a, V3a, tha, tau2a, tau3a, pa, dpdta, q2a, q3a)

end subroutine write_all_output


subroutine darcy_component(t, k, comp, qval)
  use bp8_module
  implicit none
  real(DP), intent(in) :: t
  integer, intent(in) :: k, comp
  real(DP), intent(out) :: qval
  integer :: i0, j0, i1, j1, k1a, k2a, k1b, k2b
  real(DP) :: p_a, p_b, dpdt_dummy, k_over_eta

  call k_to_ij(k, n_side, i0, j0)
  k_over_eta = alpha_diff * beta_diff * phi_diff

  if (comp == 2) then
    i1 = max(0, i0 - 1)
    call ij_to_k(min(n_side-1,i0+1), j0, n_side, k1a, k2a)
    call ij_to_k(i1, j0, n_side, k1b, k2b)
  else
    j1 = max(0, j0 - 1)
    call ij_to_k(i0, min(n_side-1,j0+1), n_side, k1a, k2a)
    call ij_to_k(i0, j1, n_side, k1b, k2b)
  end if

  call pf_lookup(t, k1a, p_a, dpdt_dummy)
  call pf_lookup(t, k1b, p_b, dpdt_dummy)
  ! call again with the second triangle of each neighboring cell and average
  block
    real(DP) :: p_a2, p_b2
    call pf_lookup(t, k2a, p_a2, dpdt_dummy)
    call pf_lookup(t, k2b, p_b2, dpdt_dummy)
    p_a = 0.5_DP * (p_a + p_a2)
    p_b = 0.5_DP * (p_b + p_b2)
  end block

  qval = -k_over_eta * (p_a - p_b) / (2.0_DP * dz_cell)
end subroutine darcy_component


subroutine write_station_row(unit_no, t, x2q, x3q, n_side, dz, half, &
    s2a, s3a, V2a, V3a, tau2a, tau3a, pa, q2a, q3a, tha, Nt_all)
  use bp8_module, only: DP
  implicit none
  integer, intent(in) :: unit_no, n_side, Nt_all
  real(DP), intent(in) :: t, x2q, x3q, dz, half
  real(DP), intent(in) :: s2a(Nt_all), s3a(Nt_all), V2a(Nt_all), V3a(Nt_all)
  real(DP), intent(in) :: tau2a(Nt_all), tau3a(Nt_all), pa(Nt_all), q2a(Nt_all), q3a(Nt_all)
  real(DP), intent(in) :: tha(Nt_all)
  real(DP) :: s2v, s3v, V2v, V3v, tau2v, tau3v, pv, q2v, q3v, thv
  real(DP) :: cellf(n_side, n_side)
  real(DP) :: bilinear_cell
  external :: bilinear_cell

  call build_cell_field(s2a, Nt_all, n_side, cellf); s2v = bilinear_cell(cellf, n_side, dz, half, x2q, x3q)
  call build_cell_field(s3a, Nt_all, n_side, cellf); s3v = bilinear_cell(cellf, n_side, dz, half, x2q, x3q)
  call build_cell_field(V2a, Nt_all, n_side, cellf); V2v = bilinear_cell(cellf, n_side, dz, half, x2q, x3q)
  call build_cell_field(V3a, Nt_all, n_side, cellf); V3v = bilinear_cell(cellf, n_side, dz, half, x2q, x3q)
  call build_cell_field(tau2a, Nt_all, n_side, cellf); tau2v = bilinear_cell(cellf, n_side, dz, half, x2q, x3q)
  call build_cell_field(tau3a, Nt_all, n_side, cellf); tau3v = bilinear_cell(cellf, n_side, dz, half, x2q, x3q)
  call build_cell_field(pa, Nt_all, n_side, cellf); pv = bilinear_cell(cellf, n_side, dz, half, x2q, x3q)
  call build_cell_field(q2a, Nt_all, n_side, cellf); q2v = bilinear_cell(cellf, n_side, dz, half, x2q, x3q)
  call build_cell_field(q3a, Nt_all, n_side, cellf); q3v = bilinear_cell(cellf, n_side, dz, half, x2q, x3q)
  call build_cell_field(tha, Nt_all, n_side, cellf); thv = bilinear_cell(cellf, n_side, dz, half, x2q, x3q)

  write(unit_no,'(E22.14,10E15.7)') t, s2v, s3v, &
      log10(max(abs(V2v),1.0d-20)), log10(max(abs(V3v),1.0d-20)), &
      tau2v/1.0d6, tau3v/1.0d6, pv/1.0d6, q2v, q3v, log10(max(thv,1.0d-20))
end subroutine write_station_row


! Query points are the FIXED BP8-required grid (-lf_fixed to lf_fixed at
! node_dz_fixed=10m, n_nodes_fixed=81 nodes; see bp8_module.f90) regardless
! of the mesh's own resolution/domain size. n_side/dz/half here describe
! the MESH's own (interpolation-source) grid, passed through to
! build_cell_field/bilinear_cell -- a coarser or larger mesh just means
! the same fixed query points get interpolated from a coarser or
! differently-sized source grid.
subroutine write_profile_row(unit_no, t, Vmax, axis, field, n_side, dz, half, Nt_all)
  use bp8_module, only: DP, lf_fixed, n_nodes_fixed, node_dz_fixed
  implicit none
  integer, intent(in) :: unit_no, n_side, Nt_all
  real(DP), intent(in) :: t, Vmax, dz, half
  character(len=2), intent(in) :: axis
  real(DP), intent(in) :: field(Nt_all)
  integer :: i
  real(DP) :: row(n_nodes_fixed)
  real(DP) :: node, cellf(n_side, n_side)
  real(DP) :: bilinear_cell
  external :: bilinear_cell
  character(len=32) :: fmt_str

  call build_cell_field(field, Nt_all, n_side, cellf)

  do i = 1, n_nodes_fixed
    node = -lf_fixed + real(i-1, DP) * node_dz_fixed
    if (axis == 'x2') then
      row(i) = bilinear_cell(cellf, n_side, dz, half, node, 0.0_DP)
    else
      row(i) = bilinear_cell(cellf, n_side, dz, half, 0.0_DP, node)
    end if
  end do

  write(fmt_str,'(A,I0,A)') '(2E22.14,', n_nodes_fixed, 'E15.7)'
  write(unit_no,fmt_str) t, log10(max(Vmax,1.0d-20)), row
end subroutine write_profile_row
